# Generated by Django 3.1.2 on 2021-05-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mamography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(null=True, upload_to='mamografias')),
                ('birad', models.CharField(max_length=50, verbose_name='tipo de cancer')),
            ],
            options={
                'verbose_name': 'mamografia',
                'verbose_name_plural': 'mamografias',
                'ordering': ['birad'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('passwor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'ordering': ['id'],
            },
        ),
    ]
