# Generated by Django 3.1.2 on 2021-06-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mamography',
            name='imagen',
            field=models.ImageField(null=True, upload_to='mamografias'),
        ),
    ]
