# Generated by Django 3.1.2 on 2021-05-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='imagen',
            field=models.FileField(null=True, upload_to='mamografias'),
        ),
    ]
