# Generated by Django 3.1.2 on 2021-05-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210528_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='passwor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
