# Generated by Django 3.1.2 on 2021-06-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210602_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mamography',
            name='birad',
            field=models.CharField(blank=True, max_length=50, verbose_name='tipo de cancer'),
        ),
    ]
