# Generated by Django 3.1.2 on 2021-05-30 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_medico_passwor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['usuario'], 'verbose_name': 'Medico', 'verbose_name_plural': 'Medicos'},
        ),
        migrations.RemoveField(
            model_name='medico',
            name='nombre',
        ),
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
